image: python

stages: 
  - run
  - deploy

before_script:
  - python -V  # Print out python version for debugging

run:
  script:
    - pip install pandas
    - python readCSVFile.py 
  
deploy:
  script:
    - echo "Deployment"
