image: python

stages: 
  - run
  - deploy

before_script:
  - python -V  # Print out python version for debugging

job1:
  stage: run
  script:
    - pip install pandas
    - python readCSVFile.py 
  
job2:
  stage: deploy
  script:
    - echo "Deployment"
