image: python

variables:
  PIP_CACHE: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install pandas

stages: 
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo "Test job1"

job2 :
  stage: test
  script :
    - python readCSVFile.py test

job3 :
  stage: deploy
  script :
    - echo "Deploy"