stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  image: python
  script: 
    - python -v
    - pip install pandas

job 3:
  stage: test
  script: 
    - python readCSVFile.csv

job 4:
  stage: deploy
  script: 
    - echo "Deployment"

