stages: 
  - build
  - test

job1:
  stage: build
  script:
    - echo "Test job1"

job2 :
  image: python
  stage: test
  script :
    - pip install pandas
    - python readCSVFile.py test
  artifacts:
    paths:
      - output/test.txt
    expire_in: 1 days