version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            pip install pandas
            python readCSVFill.py test