version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
           python3 -m venv venv
            . venv/bin/activate
            pip install pandas
job2:
  steps:
     - run:
          command: |
            . venv/bin/activate
            pwd    
            ls
            cat readCSVFile.py            
            python3 readCSVFile.py   
