version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            pwd    
            ls
            cat readCSVFile.py
            pip install pandas
            python3 readCSVFile.py