version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          command: |
            python readCSVFill.py test