version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            pipenv install
            pipenv run python readCSVFill.py test