version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - job1:
          command: |
            pip install pandas
      - run:
          command: |
            pwd    
            ls
            cat readCSVFile.py            
            python3 readCSVFile.py