version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
           python3 -m venv venv
            . venv/bin/activate
            pip install pandas
      - run:
          command: |
            
              
            python3 readCSVFile.py   
     
